### PR TITLE
Add project setup using vite cli, react and chakra ui

### PR DESCRIPTION
**Pull request by Lirak-f**

### CODE REVIEW

**Comment by wei** [comment]
Could we add a eslint of some sort or prettier, etc so we are not using tabs?

**Comment by wei** [comment]
Overall this is looking great short and sweet.

**Comment by Lirak-f** [comment]
@wei Added eslint and prettier, please re-check!

**Review by wei — CHANGES_REQUESTED** [review]
chakra-ui is not in package.json 

```
[plugin:vite:import-analysis] Failed to resolve import "@chakra-ui/react" from "src/main.tsx". Does the file exist?
```

Could you delete node_module, install chakra-ui and make sure everything works from a fresh npm i?

**Comment by Lirak-f** [comment]
Very weird I did that even earlier and it was working. Added chakra-ui to dependencies.

**Review by wei — APPROVED** [review]
Looking awesome!! Thanks for setting this up!

**Pull request merged**
